#nullable enable

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace ComputerClubWinForms.Forms;

partial class MainForm
{
    private Panel _headerPanel = null!;
    private Label _currentUserLabel = null!;
    private Button _logoutButton = null!;
    private TabControl _mainTabControl = null!;
    private TabPage _tabClients = null!;
    private TabPage _tabSessions = null!;
    private TabPage _tabReports = null!;
    private TabPage _tabSettings = null!;
    private Label _sessionsPlaceholderLabel = null!;
    private Label _reportsPlaceholderLabel = null!;
    private Label _settingsPlaceholderLabel = null!;

    private void InitializeComponent()
    {
        _headerPanel = new Panel();
        _currentUserLabel = new Label();
        _logoutButton = new Button();
        _mainTabControl = new TabControl();
        _tabClients = new TabPage();
        _tabSessions = new TabPage();
        _sessionsPlaceholderLabel = new Label();
        _tabReports = new TabPage();
        _reportsPlaceholderLabel = new Label();
        _tabSettings = new TabPage();
        _settingsPlaceholderLabel = new Label();
        _headerPanel.SuspendLayout();
        _mainTabControl.SuspendLayout();
        _tabSessions.SuspendLayout();
        _tabReports.SuspendLayout();
        _tabSettings.SuspendLayout();
        SuspendLayout();
        _headerPanel.Controls.Add(_currentUserLabel);
        _headerPanel.Controls.Add(_logoutButton);
        _headerPanel.Dock = DockStyle.Top;
        _headerPanel.Location = new Point(0, 0);
        _headerPanel.Name = "_headerPanel";
        _headerPanel.Padding = new Padding(14, 8, 14, 8);
        _headerPanel.Size = new Size(1100, 48);
        _headerPanel.TabIndex = 0;
        _currentUserLabel.AutoSize = true;
        _currentUserLabel.Location = new Point(14, 16);
        _currentUserLabel.Name = "_currentUserLabel";
        _currentUserLabel.Size = new Size(332, 15);
        _currentUserLabel.TabIndex = 0;
        _currentUserLabel.Text = "Пользователь: admin | Роль: admin (пример конструктора)";
        _currentUserLabel.TextAlign = ContentAlignment.MiddleLeft;
        _logoutButton.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        _logoutButton.Location = new Point(976, 10);
        _logoutButton.Name = "_logoutButton";
        _logoutButton.Size = new Size(110, 28);
        _logoutButton.TabIndex = 1;
        _logoutButton.Text = "Выйти";
        _logoutButton.UseVisualStyleBackColor = true;
        _logoutButton.Click += OnLogoutClick;
        _mainTabControl.Controls.Add(_tabClients);
        _mainTabControl.Controls.Add(_tabSessions);
        _mainTabControl.Controls.Add(_tabReports);
        _mainTabControl.Controls.Add(_tabSettings);
        _mainTabControl.Dock = DockStyle.Fill;
        _mainTabControl.Location = new Point(0, 48);
        _mainTabControl.Name = "_mainTabControl";
        _mainTabControl.SelectedIndex = 0;
        _mainTabControl.Size = new Size(1100, 672);
        _mainTabControl.TabIndex = 1;
        _tabClients.Location = new Point(4, 24);
        _tabClients.Name = "_tabClients";
        _tabClients.Padding = new Padding(12);
        _tabClients.Size = new Size(1092, 644);
        _tabClients.TabIndex = 0;
        _tabClients.Text = "Клиенты";
        _tabClients.UseVisualStyleBackColor = true;
        _tabSessions.Controls.Add(_sessionsPlaceholderLabel);
        _tabSessions.Location = new Point(4, 24);
        _tabSessions.Name = "_tabSessions";
        _tabSessions.Padding = new Padding(12);
        _tabSessions.Size = new Size(1092, 644);
        _tabSessions.TabIndex = 1;
        _tabSessions.Text = "Сеансы";
        _tabSessions.UseVisualStyleBackColor = true;
        _sessionsPlaceholderLabel.AutoSize = true;
        _sessionsPlaceholderLabel.Location = new Point(12, 12);
        _sessionsPlaceholderLabel.Name = "_sessionsPlaceholderLabel";
        _sessionsPlaceholderLabel.Size = new Size(520, 15);
        _sessionsPlaceholderLabel.TabIndex = 0;
        _sessionsPlaceholderLabel.Text = "Во время запуска сюда подставляется SessionPage. Отдельно её можно открыть в дизайнере.";
        _tabReports.Controls.Add(_reportsPlaceholderLabel);
        _tabReports.Location = new Point(4, 24);
        _tabReports.Name = "_tabReports";
        _tabReports.Padding = new Padding(12);
        _tabReports.Size = new Size(1092, 644);
        _tabReports.TabIndex = 2;
        _tabReports.Text = "Отчёты";
        _tabReports.UseVisualStyleBackColor = true;
        _reportsPlaceholderLabel.AutoSize = true;
        _reportsPlaceholderLabel.Location = new Point(12, 12);
        _reportsPlaceholderLabel.Name = "_reportsPlaceholderLabel";
        _reportsPlaceholderLabel.Size = new Size(516, 15);
        _reportsPlaceholderLabel.TabIndex = 0;
        _reportsPlaceholderLabel.Text = "Во время запуска сюда подставляется ReportPage. Отдельно её можно открыть в дизайнере.";
        _tabSettings.Controls.Add(_settingsPlaceholderLabel);
        _tabSettings.Location = new Point(4, 24);
        _tabSettings.Name = "_tabSettings";
        _tabSettings.Padding = new Padding(12);
        _tabSettings.Size = new Size(1092, 644);
        _tabSettings.TabIndex = 3;
        _tabSettings.Text = "Настройки";
        _tabSettings.UseVisualStyleBackColor = true;
        _settingsPlaceholderLabel.AutoSize = true;
        _settingsPlaceholderLabel.Location = new Point(12, 12);
        _settingsPlaceholderLabel.Name = "_settingsPlaceholderLabel";
        _settingsPlaceholderLabel.Size = new Size(523, 15);
        _settingsPlaceholderLabel.TabIndex = 0;
        _settingsPlaceholderLabel.Text = "Во время запуска сюда подставляется SettingsPage. Отдельно её можно открыть в дизайнере.";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1100, 720);
        Controls.Add(_mainTabControl);
        Controls.Add(_headerPanel);
        MinimumSize = new Size(1100, 720);
        Name = "MainForm";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Компьютерный клуб — управление сеансами";
        WindowState = FormWindowState.Maximized;
        _headerPanel.ResumeLayout(false);
        _headerPanel.PerformLayout();
        _mainTabControl.ResumeLayout(false);
        _tabSessions.ResumeLayout(false);
        _tabSessions.PerformLayout();
        _tabReports.ResumeLayout(false);
        _tabReports.PerformLayout();
        _tabSettings.ResumeLayout(false);
        _tabSettings.PerformLayout();
        ResumeLayout(false);
    }
}
